name: docs
# Based on https://squidfunk.github.io/mkdocs-material/publishing-your-site/
on:
  push:
    tags:
      - "v*.*.*"
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      # TODO get rid of python version here once you get this working.
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pdm install -G docs --no-self
      - run: pdm run mkdocs gh-deploy --force
