# This workflow will install project dependencies and run linter
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  ci:
    strategy:
      matrix:
        python-version: ["3.12"]
        poetry-version: ["1.8.1"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4

      - name: Install dependencies
        run: pdm install -G lint,build

      - name: Run ruff lint check
        run: pdm run ruff check .

      - name: Run ruff format check
        run: pdm run ruff format --check .

      - name: Run Cython lint
        run: pdm run cython-lint .

      - name: Run mypy
        run: pdm run mypy .
