# This workflow will install project dependencies and run linter
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.10"
          cache: true

      - name: Install dependencies
        run: pdm install -G lint --no-self

      - name: Run ruff lint check
        run: pdm run ruff check .

      - name: Run ruff format check
        run: pdm run ruff format --check .

      - name: Run Cython lint
        run: pdm run cython-lint .

      - name: Run mypy
        run: pdm run mypy .
