name: tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          version: latest
          python-version: 3.10

      - name: Install dependencies
        run: pdm install -G test,build

      - name: Run tests
        run: pdm run pytest
